# Generated by Django 3.1.2 on 2020-10-22 05:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ParticipantInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ph_no', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=100)),
                ('other_membership', models.TextField(blank=True)),
                ('company_nm', models.CharField(max_length=50)),
                ('applicant_desig', models.CharField(max_length=25)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
