# Generated by Django 3.1.2 on 2020-10-29 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BAI_app_v2', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Speed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tender', models.CharField(choices=[('yes', 'yes'), ('no', 'no')], max_length=4)),
                ('ProTimeFrame', models.TextField(blank=True, max_length=100)),
                ('tracked', models.CharField(choices=[('yes', 'yes'), ('no', 'no')], max_length=4)),
                ('PMCappointed', models.CharField(choices=[('yes', 'yes'), ('no', 'no')], max_length=4)),
                ('TimeReduc', models.CharField(choices=[('yes', 'yes'), ('no', 'no')], max_length=4)),
                ('trackPro', models.CharField(choices=[('yes', 'yes'), ('no', 'no')], max_length=4)),
                ('expectPeriod', models.TextField(max_length=100)),
                ('periodComplete', models.TextField(max_length=100)),
                ('difficulty', models.CharField(choices=[('yes', 'yes'), ('no', 'no')], max_length=4)),
                ('timeLost', models.TextField(blank=True, max_length=100)),
                ('mechanization', models.CharField(blank=True, choices=[('yes', 'yes'), ('no', 'no')], max_length=4)),
                ('contribImprov', models.TextField(blank=True, max_length=100)),
                ('tenderPay', models.CharField(choices=[('yes', 'yes'), ('no', 'no')], max_length=4)),
                ('suggest', models.TextField(max_length=100)),
                ('SpeedScale', models.CharField(choices=[('yes', 'yes'), ('no', 'no')], max_length=4)),
            ],
        ),
    ]
