# Generated by Django 3.1.2 on 2020-10-29 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BAI_app_v2', '0002_speed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speed',
            name='SpeedScale',
            field=models.TextField(max_length=100),
        ),
    ]
