# Generated by Django 3.1.2 on 2020-10-30 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BAI_app_v2', '0007_auto_20201030_1226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='others',
            name='accomodation',
            field=models.ImageField(blank=True, upload_to='uploads'),
        ),
        migrations.AlterField(
            model_name='others',
            name='polution_measures',
            field=models.ImageField(blank=True, upload_to='uploads'),
        ),
        migrations.AlterField(
            model_name='others',
            name='sanitary',
            field=models.ImageField(blank=True, upload_to='uploads'),
        ),
    ]
