# Generated by Django 3.1.2 on 2020-10-30 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BAI_app_v2', '0008_auto_20201030_1448'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='safetynwellfare',
            name='bywhom',
        ),
        migrations.RemoveField(
            model_name='safetynwellfare',
            name='incidents',
        ),
        migrations.RemoveField(
            model_name='safetynwellfare',
            name='measures',
        ),
        migrations.RemoveField(
            model_name='safetynwellfare',
            name='medical_aid',
        ),
        migrations.RemoveField(
            model_name='safetynwellfare',
            name='monitered',
        ),
        migrations.RemoveField(
            model_name='safetynwellfare',
            name='safety_audits',
        ),
    ]
