# Generated by Django 3.1.2 on 2020-10-30 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BAI_app_v2', '0009_auto_20201030_2241'),
    ]

    operations = [
        migrations.AddField(
            model_name='safetynwellfare',
            name='bywhom',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='safetynwellfare',
            name='incidents',
            field=models.CharField(blank=True, choices=[('on', 'on'), ('off', 'off')], max_length=4),
        ),
        migrations.AddField(
            model_name='safetynwellfare',
            name='measures',
            field=models.TextField(blank=True, max_length=2000),
        ),
        migrations.AddField(
            model_name='safetynwellfare',
            name='medical_aid',
            field=models.CharField(blank=True, choices=[('on', 'on'), ('off', 'off')], max_length=4),
        ),
        migrations.AddField(
            model_name='safetynwellfare',
            name='monitered',
            field=models.CharField(blank=True, choices=[('on', 'on'), ('off', 'off')], max_length=4),
        ),
        migrations.AddField(
            model_name='safetynwellfare',
            name='safety_audits',
            field=models.FileField(blank=True, upload_to='uploads'),
        ),
    ]
