# Generated by Django 3.1.2 on 2020-10-31 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BAI_app_v2', '0011_auto_20201030_2313'),
    ]

    operations = [
        migrations.CreateModel(
            name='Economy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_cost', models.FloatField()),
                ('who_determined', models.TextField(max_length=255)),
                ('cost_reduction', models.CharField(choices=[('on', 'yes'), ('off', 'no')], max_length=4)),
                ('tracked_e', models.CharField(blank=True, choices=[('on', 'yes'), ('off', 'no')], max_length=4)),
                ('who_tracked', models.TextField(blank=True, max_length=255)),
                ('PMC_appointed', models.CharField(blank=True, choices=[('on', 'yes'), ('off', 'no')], max_length=4)),
                ('expected_cost', models.FloatField()),
                ('actual_cost', models.FloatField()),
                ('difficulty_e', models.CharField(blank=True, choices=[('on', 'yes'), ('off', 'no')], max_length=4)),
                ('escalated', models.TextField(blank=True, max_length=255)),
                ('costsaving_measures', models.TextField(max_length=255)),
                ('suggestions', models.TextField(blank=True, max_length=255)),
                ('cost_per_sft', models.FloatField()),
                ('cost_per_room', models.FloatField()),
                ('cost_per_bed', models.FloatField()),
                ('cost_per_workstation', models.FloatField()),
                ('cost_per_similar', models.FloatField()),
                ('economy_ratings', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], max_length=4)),
            ],
        ),
        migrations.AlterField(
            model_name='others',
            name='ISO_accreditation',
            field=models.CharField(blank=True, choices=[('on', 'yes'), ('off', 'no')], max_length=4),
        ),
        migrations.AlterField(
            model_name='others',
            name='accomodation',
            field=models.ImageField(upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='others',
            name='polution_measures',
            field=models.ImageField(upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='others',
            name='renewable_energy_pic',
            field=models.FileField(blank=True, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='others',
            name='sanitary',
            field=models.ImageField(upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='others',
            name='school',
            field=models.ImageField(blank=True, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='safetynwellfare',
            name='incidents',
            field=models.CharField(choices=[('on', 'yes'), ('off', 'no')], max_length=10),
        ),
        migrations.AlterField(
            model_name='safetynwellfare',
            name='measures',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='safetynwellfare',
            name='medical_aid',
            field=models.CharField(choices=[('on', 'yes'), ('off', 'no')], max_length=10),
        ),
        migrations.AlterField(
            model_name='safetynwellfare',
            name='monitered',
            field=models.CharField(choices=[('on', 'yes'), ('off', 'no')], max_length=10),
        ),
        migrations.AlterField(
            model_name='safetynwellfare',
            name='safety_audits',
            field=models.FileField(blank=True, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='speed',
            name='PMCappointed',
            field=models.CharField(choices=[('on', 'yes'), ('off', 'no')], max_length=4),
        ),
        migrations.AlterField(
            model_name='speed',
            name='TimeReduc',
            field=models.CharField(choices=[('on', 'yes'), ('off', 'no')], max_length=4),
        ),
        migrations.AlterField(
            model_name='speed',
            name='difficulty',
            field=models.CharField(choices=[('on', 'yes'), ('off', 'no')], max_length=4),
        ),
        migrations.AlterField(
            model_name='speed',
            name='tender',
            field=models.CharField(choices=[('on', 'yes'), ('off', 'no')], max_length=4),
        ),
        migrations.AlterField(
            model_name='speed',
            name='tenderPay',
            field=models.CharField(choices=[('on', 'yes'), ('off', 'no')], max_length=4),
        ),
        migrations.AlterField(
            model_name='speed',
            name='trackPro',
            field=models.CharField(choices=[('on', 'yes'), ('off', 'no')], max_length=4),
        ),
        migrations.AlterField(
            model_name='speed',
            name='tracked',
            field=models.CharField(choices=[('on', 'yes'), ('off', 'no')], max_length=4),
        ),
    ]
