# Generated by Django 3.1.2 on 2020-10-31 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BAI_app_v2', '0012_auto_20201031_1115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='economy',
            name='economy_ratings',
            field=models.TextField(max_length=100),
        ),
    ]
