# Generated by Django 3.1.2 on 2020-11-01 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BAI_app_v2', '0013_auto_20201031_2356'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.TextField(max_length=200)),
                ('project_address', models.TextField(max_length=200)),
                ('site_map', models.FileField(blank=True, upload_to='uploads/')),
                ('client_name', models.TextField(max_length=200)),
                ('project_cost', models.IntegerField(max_length=200)),
                ('applicant_role', models.TextField(max_length=200)),
                ('applicant_scope', models.TextField(max_length=200)),
                ('applicantWork_cost', models.IntegerField(max_length=200)),
                ('time_limit', models.DateTimeField(blank=True)),
                ('commencement_date', models.DateTimeField()),
                ('sched_completion_date', models.DateTimeField()),
                ('act_completion_date', models.DateTimeField()),
                ('proj_cost_tilldate', models.IntegerField(max_length=200)),
                ('Architect_name', models.CharField(blank=True, max_length=200)),
                ('Structural_Consultant_name', models.CharField(blank=True, max_length=200)),
                ('Plumbing_Consultant_name', models.CharField(blank=True, max_length=200)),
                ('Fire_Consultant_name', models.CharField(blank=True, max_length=200)),
                ('Landscaping_Consultant_name', models.CharField(blank=True, max_length=200)),
                ('HVAC_Consultant_name', models.CharField(blank=True, max_length=200)),
                ('Electrical_Consultant_name', models.CharField(blank=True, max_length=200)),
                ('Interior_Designer_name', models.CharField(blank=True, max_length=200)),
                ('Project_Management_Consultant_name', models.CharField(blank=True, max_length=200)),
                ('MoEF_Consultant_name', models.CharField(blank=True, max_length=200)),
                ('req_docs', models.FileField(blank=True, upload_to='uploads/')),
                ('green_proj', models.CharField(blank=True, choices=[('on', 'yes'), ('off', 'no')], max_length=1000)),
                ('green_project_details', models.FileField(blank=True, upload_to='uploads/')),
            ],
        ),
        migrations.CreateModel(
            name='Quality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('any_system_for_coordinating_of_all_drawings', models.CharField(blank=True, choices=[('on', 'yes'), ('off', 'no')], max_length=1000)),
                ('drawing_coordinating_system', models.CharField(blank=True, choices=[('on', 'yes'), ('off', 'no')], max_length=1000)),
                ('PMC', models.CharField(blank=True, choices=[('on', 'yes'), ('off', 'no')], max_length=1000)),
                ('drawing_specification_assessment', models.CharField(choices=[('on', 'yes'), ('off', 'no')], max_length=1000)),
                ('consultant_visit_frequency', models.IntegerField(blank=True, max_length=20)),
                ('Decision_recorded', models.CharField(choices=[('on', 'yes'), ('off', 'no')], max_length=1000)),
                ('meeting_instruction_book_minute', models.FileField(blank=True, upload_to='uploads/')),
                ('quality_standard_tender', models.CharField(choices=[('on', 'yes'), ('off', 'no')], max_length=1000)),
                ('name_of_quality_standard_approver', models.CharField(max_length=1000)),
                ('in_house_team_quality_control', models.CharField(blank=True, choices=[('on', 'yes'), ('off', 'no')], max_length=1000)),
                ('external_team_to_control_quality', models.CharField(blank=True, choices=[('on', 'yes'), ('off', 'no')], max_length=1000)),
                ('list_quality_assurance_tests_OnSite', models.TextField(max_length=100)),
                ('list_quality_assurance_tests_Off_Site', models.TextField(max_length=100)),
                ('sample_Checklist_followed', models.FileField(blank=True, upload_to='uploads/')),
                ('sample_test_reports', models.FileField(blank=True, upload_to='uploads/')),
                ('any_special_training_programs', models.CharField(blank=True, choices=[('on', 'yes'), ('off', 'no')], max_length=1000)),
                ('If_Yes_Provide_details', models.TextField(blank=True, max_length=100)),
                ('any_Supervision_from_Client_side', models.CharField(choices=[('on', 'yes'), ('off', 'no')], max_length=1000)),
                ('Any_other_system_method_mechanism_adopted', models.CharField(choices=[('on', 'yes'), ('off', 'no')], max_length=1000)),
                ('system_method_mechanism_adopted', models.TextField(blank=True, max_length=100)),
                ('rate_your_project_in_terms_of_quality', models.IntegerField(max_length=20)),
            ],
        ),
    ]
