# Generated by Django 3.1.2 on 2020-11-01 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BAI_app_v2', '0015_auto_20201101_1902'),
    ]

    operations = [
        migrations.AddField(
            model_name='quality',
            name='If_Yes_Provide_details_workers',
            field=models.TextField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='quality',
            name='any_special_training_programs_workers',
            field=models.CharField(blank=True, choices=[('on', 'yes'), ('off', 'no')], max_length=1000),
        ),
        migrations.AlterField(
            model_name='quality',
            name='Any_other_system_method_mechanism_adopted',
            field=models.CharField(blank=True, choices=[('on', 'yes'), ('off', 'no')], max_length=1000),
        ),
        migrations.AlterField(
            model_name='quality',
            name='drawing_coordinating_system',
            field=models.TextField(blank=True, max_length=1000),
        ),
    ]
