# Generated by Django 3.1.2 on 2020-11-01 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BAI_app_v2', '0016_auto_20201101_1919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quality',
            name='name_of_quality_standard_approver',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
