# Generated by Django 3.1.2 on 2020-11-01 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BAI_app_v2', '0017_auto_20201101_1928'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project_info',
            name='time_limit',
        ),
    ]
