# Generated by Django 3.1.2 on 2020-11-10 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BAI_app_v2', '0018_remove_project_info_time_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='safetynwellfare',
            name='users_name',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
