# Generated by Django 3.1.2 on 2020-11-28 06:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BAI_app_v2', '0021_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='app_form_cat',
            field=models.CharField(max_length=4),
        ),
        migrations.CreateModel(
            name='CategoryChoices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.CharField(max_length=100, verbose_name='CategoryChoices')),
                ('app_form_cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='BAI_app_v2.category')),
            ],
            options={
                'unique_together': {('app_form_cat', 'choice')},
            },
        ),
    ]
