# Generated by Django 3.1.2 on 2020-11-28 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BAI_app_v2', '0022_auto_20201128_1204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='app_form_cat',
            field=models.CharField(blank=True, max_length=4),
        ),
    ]
