# Generated by Django 3.1.2 on 2020-10-29 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BAI_app_v2', '0003_auto_20201029_2244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speed',
            name='PMCappointed',
            field=models.CharField(choices=[('on', 'on'), ('off', 'off')], max_length=4),
        ),
        migrations.AlterField(
            model_name='speed',
            name='TimeReduc',
            field=models.CharField(choices=[('on', 'on'), ('off', 'off')], max_length=4),
        ),
        migrations.AlterField(
            model_name='speed',
            name='difficulty',
            field=models.CharField(choices=[('on', 'on'), ('off', 'off')], max_length=4),
        ),
        migrations.AlterField(
            model_name='speed',
            name='mechanization',
            field=models.CharField(blank=True, choices=[('on', 'on'), ('off', 'off')], max_length=4),
        ),
        migrations.AlterField(
            model_name='speed',
            name='tender',
            field=models.CharField(choices=[('on', 'on'), ('off', 'off')], max_length=4),
        ),
        migrations.AlterField(
            model_name='speed',
            name='tenderPay',
            field=models.CharField(choices=[('on', 'on'), ('off', 'off')], max_length=4),
        ),
        migrations.AlterField(
            model_name='speed',
            name='trackPro',
            field=models.CharField(choices=[('on', 'on'), ('off', 'off')], max_length=4),
        ),
        migrations.AlterField(
            model_name='speed',
            name='tracked',
            field=models.CharField(choices=[('on', 'on'), ('off', 'off')], max_length=4),
        ),
    ]
