# Generated by Django 3.1.2 on 2020-10-30 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BAI_app_v2', '0006_others_safetynwellfare'),
    ]

    operations = [
        migrations.AlterField(
            model_name='others',
            name='accomodation',
            field=models.ImageField(upload_to='uploads'),
        ),
        migrations.AlterField(
            model_name='others',
            name='polution_measures',
            field=models.ImageField(upload_to='uploads'),
        ),
        migrations.AlterField(
            model_name='others',
            name='renewable_energy_pic',
            field=models.FileField(blank=True, upload_to='uploads'),
        ),
        migrations.AlterField(
            model_name='others',
            name='sanitary',
            field=models.ImageField(upload_to='uploads'),
        ),
        migrations.AlterField(
            model_name='others',
            name='school',
            field=models.ImageField(blank=True, upload_to='uploads'),
        ),
        migrations.AlterField(
            model_name='safetynwellfare',
            name='safety_audits',
            field=models.FileField(blank=True, upload_to='uploads'),
        ),
    ]
