# Generated by Django 3.1.2 on 2020-11-01 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BAI_app_v2', '0014_project_info_quality'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project_info',
            name='applicantWork_cost',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='project_info',
            name='proj_cost_tilldate',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='project_info',
            name='project_cost',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='quality',
            name='consultant_visit_frequency',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='quality',
            name='rate_your_project_in_terms_of_quality',
            field=models.IntegerField(),
        ),
    ]
