# Generated by Django 3.1.2 on 2020-11-10 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BAI_app_v2', '0019_safetynwellfare_users_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='economy',
            name='users_name',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='others',
            name='users_name',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='project_info',
            name='users_name',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='quality',
            name='users_name',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='speed',
            name='users_name',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
