# Generated by Django 3.1.2 on 2020-11-29 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BAI_app_v2', '0026_auto_20201129_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='cat1',
            field=models.CharField(blank=True, default='off', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='cat2',
            field=models.CharField(blank=True, default='off', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='cat3',
            field=models.CharField(blank=True, default='off', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='cat4',
            field=models.CharField(blank=True, default='off', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='cat5',
            field=models.CharField(blank=True, default='off', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='cat6',
            field=models.CharField(blank=True, default='off', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='cat7',
            field=models.CharField(blank=True, default='off', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='cat8',
            field=models.CharField(blank=True, default='off', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='cat9',
            field=models.CharField(blank=True, default='off', max_length=100, unique=True),
        ),
    ]
