# Generated by Django 3.1.2 on 2020-11-29 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BAI_app_v2', '0027_auto_20201129_1134'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='cat1',
        ),
        migrations.RemoveField(
            model_name='category',
            name='cat2',
        ),
        migrations.RemoveField(
            model_name='category',
            name='cat3',
        ),
        migrations.RemoveField(
            model_name='category',
            name='cat4',
        ),
        migrations.RemoveField(
            model_name='category',
            name='cat5',
        ),
        migrations.RemoveField(
            model_name='category',
            name='cat6',
        ),
        migrations.RemoveField(
            model_name='category',
            name='cat7',
        ),
        migrations.RemoveField(
            model_name='category',
            name='cat8',
        ),
        migrations.RemoveField(
            model_name='category',
            name='cat9',
        ),
        migrations.AddField(
            model_name='category',
            name='app_form_cat',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9')], max_length=4),
        ),
    ]
