# Generated by Django 3.1.2 on 2020-11-29 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BAI_app_v2', '0028_auto_20201129_1219'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('users_name', models.CharField(blank=True, max_length=20)),
                ('pay_method', models.CharField(max_length=50)),
                ('trans_date', models.CharField(max_length=20)),
                ('trans_id', models.CharField(max_length=30)),
                ('bank', models.CharField(max_length=50)),
            ],
        ),
    ]
