# Generated by Django 3.1.2 on 2020-12-25 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BAI_app_v2', '0030_auto_20201225_1856'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('users_name', models.CharField(blank=True, max_length=20)),
                ('category_latest', models.CharField(blank=True, max_length=2)),
            ],
        ),
    ]
