# Generated by Django 3.1.2 on 2020-12-26 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BAI_app_v2', '0033_auto_20201226_1726'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project_info_1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Architect_name', models.CharField(blank=True, max_length=200)),
                ('Structural_Consultant_name', models.CharField(blank=True, max_length=200)),
                ('Plumbing_Consultant_name', models.CharField(blank=True, max_length=200)),
                ('Fire_Consultant_name', models.CharField(blank=True, max_length=200)),
                ('Landscaping_Consultant_name', models.CharField(blank=True, max_length=200)),
                ('HVAC_Consultant_name', models.CharField(blank=True, max_length=200)),
                ('Electrical_Consultant_name', models.CharField(blank=True, max_length=200)),
                ('Interior_Designer_name', models.CharField(blank=True, max_length=200)),
                ('Project_Management_Consultant_name', models.CharField(blank=True, max_length=200)),
                ('MoEF_Consultant_name', models.CharField(blank=True, max_length=200)),
                ('req_docs', models.FileField(blank=True, upload_to='uploads/')),
                ('green_proj', models.CharField(blank=True, choices=[('on', 'yes'), ('off', 'no')], max_length=1000)),
                ('green_project_details', models.FileField(blank=True, upload_to='uploads/')),
                ('category_latest', models.CharField(blank=True, max_length=70)),
            ],
        ),
        migrations.RemoveField(
            model_name='project_info',
            name='Architect_name',
        ),
        migrations.RemoveField(
            model_name='project_info',
            name='Electrical_Consultant_name',
        ),
        migrations.RemoveField(
            model_name='project_info',
            name='Fire_Consultant_name',
        ),
        migrations.RemoveField(
            model_name='project_info',
            name='HVAC_Consultant_name',
        ),
        migrations.RemoveField(
            model_name='project_info',
            name='Interior_Designer_name',
        ),
        migrations.RemoveField(
            model_name='project_info',
            name='Landscaping_Consultant_name',
        ),
        migrations.RemoveField(
            model_name='project_info',
            name='MoEF_Consultant_name',
        ),
        migrations.RemoveField(
            model_name='project_info',
            name='Plumbing_Consultant_name',
        ),
        migrations.RemoveField(
            model_name='project_info',
            name='Project_Management_Consultant_name',
        ),
        migrations.RemoveField(
            model_name='project_info',
            name='Structural_Consultant_name',
        ),
        migrations.RemoveField(
            model_name='project_info',
            name='green_proj',
        ),
        migrations.RemoveField(
            model_name='project_info',
            name='green_project_details',
        ),
        migrations.RemoveField(
            model_name='project_info',
            name='req_docs',
        ),
        migrations.AlterField(
            model_name='economy',
            name='category_latest',
            field=models.CharField(blank=True, max_length=70),
        ),
        migrations.AlterField(
            model_name='others',
            name='category_latest',
            field=models.CharField(blank=True, max_length=70),
        ),
        migrations.AlterField(
            model_name='paymentdetails',
            name='category_latest',
            field=models.CharField(blank=True, max_length=70),
        ),
        migrations.AlterField(
            model_name='project_info',
            name='category_latest',
            field=models.CharField(blank=True, max_length=70),
        ),
        migrations.AlterField(
            model_name='quality',
            name='category_latest',
            field=models.CharField(blank=True, max_length=70),
        ),
        migrations.AlterField(
            model_name='safetynwellfare',
            name='category_latest',
            field=models.CharField(blank=True, max_length=70),
        ),
        migrations.AlterField(
            model_name='speed',
            name='category_latest',
            field=models.CharField(blank=True, max_length=70),
        ),
    ]
