# Generated by Django 3.1.2 on 2020-12-27 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BAI_app_v2', '0034_auto_20201226_2147'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='filled0',
            field=models.CharField(blank=True, choices=[('True', 'True'), ('False', 'False')], default='False', max_length=7),
        ),
        migrations.AddField(
            model_name='economy',
            name='filled2_1',
            field=models.CharField(blank=True, choices=[('True', 'True'), ('False', 'False')], default='False', max_length=7),
        ),
        migrations.AddField(
            model_name='others',
            name='filled2_3',
            field=models.CharField(blank=True, choices=[('True', 'True'), ('False', 'False')], default='False', max_length=7),
        ),
        migrations.AddField(
            model_name='paymentdetails',
            name='filled3',
            field=models.CharField(blank=True, choices=[('True', 'True'), ('False', 'False')], default='False', max_length=7),
        ),
        migrations.AddField(
            model_name='project_info',
            name='filled1_1',
            field=models.CharField(blank=True, choices=[('True', 'True'), ('False', 'False')], default='False', max_length=7),
        ),
        migrations.AddField(
            model_name='project_info_1',
            name='filled1_2',
            field=models.CharField(blank=True, choices=[('True', 'True'), ('False', 'False')], default='False', max_length=7),
        ),
        migrations.AddField(
            model_name='quality',
            name='filled1_3',
            field=models.CharField(blank=True, choices=[('True', 'True'), ('False', 'False')], default='False', max_length=7),
        ),
        migrations.AddField(
            model_name='safetynwellfare',
            name='filled2_2',
            field=models.CharField(blank=True, choices=[('True', 'True'), ('False', 'False')], default='False', max_length=7),
        ),
        migrations.AddField(
            model_name='speed',
            name='filled1_4',
            field=models.CharField(blank=True, choices=[('True', 'True'), ('False', 'False')], default='False', max_length=7),
        ),
    ]
