# Generated by Django 3.1.2 on 2020-12-29 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BAI_app_v2', '0037_category_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='filled0',
        ),
        migrations.AlterField(
            model_name='category',
            name='status',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
