# Generated by Django 3.1.2 on 2020-12-30 14:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('BAI_app_v2', '0038_auto_20201229_1742'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='filled0',
            field=models.CharField(blank=True, choices=[('True', 'True'), ('False', 'False')], default='False', max_length=7),
        ),
        migrations.AlterField(
            model_name='participantinfo',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
