# Generated by Django 3.1.2 on 2021-01-01 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BAI_app_v2', '0039_auto_20201230_1949'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='filled0',
        ),
        migrations.RemoveField(
            model_name='economy',
            name='filled2_1',
        ),
        migrations.RemoveField(
            model_name='others',
            name='filled2_3',
        ),
        migrations.RemoveField(
            model_name='paymentdetails',
            name='filled3',
        ),
        migrations.RemoveField(
            model_name='project_info',
            name='filled1_1',
        ),
        migrations.RemoveField(
            model_name='project_info_1',
            name='filled1_2',
        ),
        migrations.RemoveField(
            model_name='quality',
            name='filled1_3',
        ),
        migrations.RemoveField(
            model_name='safetynwellfare',
            name='filled2_2',
        ),
        migrations.RemoveField(
            model_name='speed',
            name='filled1_4',
        ),
    ]
