# Generated by Django 3.1.2 on 2021-01-02 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BAI_app_v2', '0040_auto_20210101_2026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='app_form_cat',
            field=models.CharField(max_length=70),
        ),
        migrations.AlterField(
            model_name='category',
            name='users_name',
            field=models.CharField(max_length=20),
        ),
    ]
