# Generated by Django 3.1.2 on 2021-01-02 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BAI_app_v2', '0041_auto_20210102_2050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='users_name',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
