# Generated by Django 3.1.2 on 2021-01-03 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BAI_app_v2', '0042_auto_20210102_2054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='app_form_cat',
            field=models.CharField(blank=True, max_length=70),
        ),
    ]
